code-is-evenly-cooked/even-zaro-front

.prettierrc, .vscode/settings.json, eslint.config.mjs, package-lock.json, package.json, src/app/globals.css, src/app/layout.tsx, src/app/page.tsx, src/layout/Layout.tsx, tailwind.config.js
- 프로젝트 초기 설정으로 ESLint, Prettier, 웹폰트 관련 설정 파일을 추가했습니다.
- 의존성 변화로 인한 오류 방지를 위해 Next.js, react, zustand 타입 고정했습니다.
- `eslint.config.mjs`: FlatConfig 기반 ESLint 설정 파일 추가
- `.prettierrc`: Prettier 포맷 규칙 설정 (싱글쿼트, 세미콜론 등)
- `.vscode/settings.json`: VSCode 저장 시 자동 포맷 및 ESLint autofix 설정
- `tailwind.config.js`: Tailwind의 `fontFamily`에 Pretendard 추가
- `globals.css`: Pretendard 웹폰트 CDN import 및 기본 폰트 적용
|폰트 적용 전|폰트 적용 후|
|:-|:-|
|<img width="111" alt="image" src="https://github.com/user-attachments/assets/115f9f2d-05c8-479e-9221-d789d6957040" />|<img width="124" alt="image" src="https://github.com/user-attachments/assets/917433ea-c0d4-4f90-ab81-efea322ae1fd" />|
- npm check를 하면 자동으로 프리티어 포맷, 린트 체크까지 완료됩니다.
현재로선 이렇게 나오고 있습니다.
=> ESLint, Prettier, Pretendard 폰트 설정 파일 추가

.npmrc, src/app/password-forget/page.tsx, src/app/password-reset/PasswordResetPageClient.tsx, src/app/password-reset/page.tsx, src/components/auth/LoginForm/LoginForm.tsx, src/components/auth/PasswordForget/PasswordForgetForm.tsx, src/components/auth/PasswordForget/usePasswordForgetForm.ts, src/components/auth/PasswordReset/PasswordResetForm.tsx, src/components/auth/PasswordReset/usePasswordResetForm.ts
비밀번호 재설정 이메일 전송화면과 비밀번호 재설정 UI를 추가했습니다.
- web IDE때 쓰던 비밀번호 재설정 이메일 전송화면 비밀번호 재설정 UI추가
- legacy-peer-deps 설정을 위한 .npmrc 추가
|비밀밀번호 재설정 이메일 전송|비밀번호 재설정|
|--|--|
|<img width="597" alt="image" src="https://github.com/user-attachments/assets/c8e8f8e6-7dfd-44b8-ba8f-feb7d8145037" />|<img width="603" alt="image" src="https://github.com/user-attachments/assets/afa799e7-3f89-4b3e-a572-74467979b639" />|
=> 비밀번호 재설정 이메일 전송화면, 비밀번호 재설정UI 추가

.npmrc, src/app/editor/EditorPageClient.tsx, src/app/editor/page.tsx, src/app/globals.css, src/components/editor/PostEditor.tsx, src/stores/usePostStore.ts, src/utils/editorStorage.ts
글 작성 페이지와 에디터의 레이아웃과 기본 설정, indexedDB 기반의 임시 저장 기능 구현
- 글 작성 페이지를 생성하고 본문 작성을 위한 Toast 에디터를 추가하였습니다
- 에디터에서 사용할 기능과 초기 설정을 진행했고 일부 UI를 수정했습니다
- 글 제목 부분과 카테고리 선택, 각종 버튼 등을 페이지에 추가했습니다
- zustand 와 indexedDB를 통해 글 카테고리와 글 제목, 본문이 전부 반영되는 임시 저장을 구현했습니다
- 전체적으로 반응형으로 작동되게 배치를 진행해봤습니다
현재 임시 저장은 5초마다 1번씩 되거나 임시 저장 버튼을 통해 가능하고
글 작성 페이지 진입 시 자동으로 불러오도록 설정되있습니다 !
임시 저장 기능 테스트 완료
npm run build 통과
확인 때문에 console.log 가 많이 들어간 상태인데, 
글 작성 api 연결 및 테스트 진행 후에 전부 지우도록 하겠습니다 !
일단 배치와 약간에 디자인만 한거라 뭔가 부족한 느낌이 엄청나네요
디자인을 조금 더 고민을 해봐야 할 것 같습니다
일단 생각에는
임시 저장 버튼을 누르면 토스트 팝업으로 성공 실패 메세지를 주면 좋을 것 같고
카테고리 선택 리스트도 IDE 때 처럼 option 이 아니라 커스텀을 해야할 것 같습니다
=> 글 작성 페이지와 에디터의 레이아웃과 기본 설정, indexedDB 기반의 임시 저장 기능 구현

.env.example, src/app/api/auth/signin/route.ts, src/app/api/auth/signup/route.ts, src/components/auth/LoginForm/useLoginForm.ts, src/components/auth/Signup/useSignupForm.ts, src/components/layout/Layout.tsx, src/lib/api/auth.ts, src/lib/auth/cookie.ts, src/lib/response.ts, src/types/auth.d.ts
이메일 회원가입 및 로그인 API를 연결했습니다.
- base url을 추가했습니다.
- api응답 핸들링을 위한 공통 response 모델을 추가했습니다.
- Route Handler를 통해 회원가입, 로그인 api를 호출하도록 했습니다.
- Route Handler를 쓰면 프론트엔드 코드에서 API URL 노출이 방지되고 서버에서 쿠키설정, 토큰 자동 주입등이 가능하다고합니다.
- signin(로그인)을 할 경우 accessToken, refreshToken을 쿠키에 저장하고 홈화면으로 이동한 후 user/my를 호출해서 사용자 정보를 전역으로 저장하려고 합니다. 이전에는 signup에서 데이터를 받아와서 저장했는데 현업에서는 홈화면 이동해서 다시 정보를 받아온다고하네요.
|회원가입 및 로그인 완료 후 users/my 호출 결과|
|--|
|<img width="1420" alt="image" src="https://github.com/user-attachments/assets/a504277d-dbef-4837-bcb9-a5daa5055703" />|
에러 핸들링은 현재는 alert로 나옵니다..
얼른 토스트 적용하도록 할게요..!
=> 이메일 회원가입 및 로그인 API연결

src/app/layout.tsx, src/components/auth/LoginForm/useLoginForm.ts, src/components/auth/Signup/useSignupForm.ts, src/components/common/Input/PasswordInput.tsx, src/components/common/ToastMessage/ToastMessageContainer.tsx, src/components/common/ToastMessage/ToastMessageItem.tsx, src/components/common/ToastMessage/index.ts, src/providers/Providers.tsx, src/providers/ToastMessageProvider.tsx, src/types/toastMessage.d.ts, tailwind.config.js
alert대신 사용할 toast를 추가했습니다.
- toast provider와 container, toast item을 추가했습니다.
alert쓰던 곳 혹은 에러나 알림 표시하려는 파일
```
const { showToastMessage } = useToastMessageContext(); 
// 표시하려는 위치
showToastMessage({ type: "error", message: errorMessage });
```
써주시면 됩니다.
useLoginForm.tsx 참고해주셔도 됩니다!
타입은 **error, success, info**가 있습니다.
현재 토스트는 하나만 표시됩니다!
|error|success|info|
|--|--|--|
|<img width="442" alt="스크린샷 2025-05-19 오후 2 28 10" src="https://github.com/user-attachments/assets/072f0b6b-4053-4665-a876-cda364320d53" />|<img width="449" alt="스크린샷 2025-05-19 오후 2 28 22" src="https://github.com/user-attachments/assets/4b4ece44-51d2-45b6-bab0-9f20e8b96585" />|<img width="459" alt="스크린샷 2025-05-19 오후 2 28 35" src="https://github.com/user-attachments/assets/aa5c52ee-91dd-43f2-b7d9-05265c11 …
=> Toast UI 추가

src/app/api/auth/signup/email-verify/route.ts, src/app/layout.tsx, src/components/auth/EmailValidation/EmailValidationForm.tsx, src/components/auth/LoginForm/useLoginForm.ts, src/components/auth/Signup/useSignupForm.ts, src/components/common/Input/PasswordInput.tsx, src/components/common/ToastMessage/ToastMessageContainer.tsx, src/components/common/ToastMessage/ToastMessageItem.tsx, src/components/common/ToastMessage/index.ts, src/lib/api/auth.ts, src/providers/Providers.tsx, src/providers/ToastMessageProvider.tsx, src/types/toastMessage.d.ts, tailwind.config.js
이메일 인증 재전송 api를 연결했습니다.
- 이메일 인증에서 인증메일 다시보내기를 클릭했을 경우 재요청하는 API를 연결했습니다.
|이메일 재 전송 중|이메일 재전송 완료|
|--|--|
|<img width="514" alt="스크린샷 2025-05-19 오후 3 52 17" src="https://github.com/user-attachments/assets/cb71c24a-61a6-4c55-9b61-fc1d50a7422c" />|<img width="855" alt="스크린샷 2025-05-19 오후 3 47 39" src="https://github.com/user-attachments/assets/85aed3eb-45d0-46b7-8eb8-dc5f3cff9b87" />|
=> 이메일 인증 재전송 API 연결

src/app/api/auth/refresh/route.ts, src/app/api/users/my/route.ts, src/components/AuthInitializer.tsx, src/lib/fetch/fetchWithAuth.client.ts, src/lib/fetch/fetchWithAuth.ts, src/providers/Providers.tsx, src/stores/useAuthStore.ts, src/types/api.ts
users/my를 통한 유저 정보 최신화 및 token refresh 적용
- API 공통 응답 핸들러를 추가했습니다.
- ssr, csr분리된 api 통신 함수 추가했습니다.
- fetchWithAuthClient -> CSR
- fetchWithAuth -> SSR
SSR일때는 route.ts 생성할 필요없이 사용하면 된다네요. 게시물 상세 같은 곳에서 쓰면 될 것 같습니다.
- AuthInitializer을 추가하여 새로고침 시 유저 정보를 최신화하고, 필요시 accessToken이 refreshe되도록 했습니다.
첨부할만한거 찾다가.. 403만난 후 /api/auth/refresh -> /api/users/my 재요청한 결과 로그입니다.
홈에서 새로고침하면 AuthInitializer에서 유저 정보 로그 찍히는 것 확인할 수 있습니다.
SSR fetch 고민하다 늦었습니다.
CSR, SSR 아직 개념이 너무 어렵네요..ㅠㅠ
=> 유저 정보 최신화 및 token refresh api현결

src/app/api/auth/refresh/route.ts, src/app/api/users/my/route.ts, src/lib/fetch/client.ts
accessToken 없을 때 무한 호출 이슈 수정
- access_token이 쿠키에 없을 때 users/my가 무한호출 되는 이슈 수정했습니다.
- 기존에는 401오류를 발생시켰는데 그러다보니 계속 다시 호출되는 이슈가 있었습니다. 
오류일 경우 오류코드가 필수로 있으야하기 때문에 성공으로 하는 대신 오류 로그를 남기도록 했습니다.
=> accessToken, refreshToken없을 경우 무한 호출 이슈 수정

next.config.ts, package-lock.json, package.json, public/icons/defaultProfile.svg, src/components/AuthInitializer.tsx, src/components/auth/LoginForm/useLoginForm.ts, src/components/common/Icons/index.tsx, src/components/layout/Header/Header.tsx, src/components/layout/HeaderShell.tsx, src/components/layout/Layout.tsx, src/lib/api/auth.ts, src/providers/Providers.tsx, src/providers/ReactQueryProvider.tsx, src/stores/useAuthStore.ts
로그인 사용자일 경우 헤더에 프로필 이미지 표시
- 로그인 사용자일 경우 헤더에 프로필 이미지가 표시되도록 했습니다.
- react query 적용했습니다.
- 새로고침 시 미로그인처럼 보이는 현상때문에 persist 적용했다가 Hydration오류 발생해서 헤더, 사이드바를 dynamic으로 로딩해오도록 변경했습니다.
- 로그인한 이후 user의 정보를 받아올 수 있도록 적용했습니다. 로그인 후 홈화면으로 이동했는데 /users/my를 호출하지 않아서 전체적으로 수정했습니다.
|프로필 사진 있을 때(카카오 로그인)|프로필사진 없을 때|
|--|--|
|<img width="464" alt="스크린샷 2025-05-22 오후 8 43 33" src="https://github.com/user-attachments/assets/cfd1ee87-45fc-4520-b7d9-a19554032a70" />|<img width="390" alt="스크린샷 2025-05-22 오후 8 43 18" src="https://github.com/user-attachments/assets/7f8420f2-2247-424a-b52a-8189507c3b08" />|
Layout에 "use client"를 사용하면 클라이언트 컴포넌트가 되는데 그럼 Next.js를 사용하는 의미가 없어지기때문에 해당 부분 고민하면서 헤더, 사이드바만 클라이언트 컴포넌트가 되도록 했습니다.
멘토링 이후 뭔가 신경쓸게 많아지니 시간이 좀 오래 걸렸네요.
=> 로그인 사용자일 경우 헤더에 프로필 이미지 표시

src/app/page.tsx, src/components/Home/HomeComponent.tsx, src/components/Home/HomeSectionCard.tsx, src/components/Home/HomeSectionHeader.tsx, src/components/Home/HomeSectionListItem.tsx, src/components/Home/SectionType.tsx, src/components/layout/Layout.tsx
홈화면 공통 헤더, 리스트 형식 공통 컴포넌트 UI 생성했습니다.
- SectionType을 생성하여 타입과 아이템만 주입하면 자동으로 UI가 그려질 수 있도록 했습니다.
- SectionType을 통해 홈 공통 헤더 UI 가 구분되도록 했습니다.
- 배경색이랑 더미데이터는 추후 삭제예정입니다!
- HomePage 자체가 SSR이 될 수 있도록 use client는 안쓸 수 있도록 컴포넌트들을 분리했습니다
- HomeComonent - 홈화면 전체의 컴포넌트를 가짐
- HomeSectionCard - 섹션별 카드
- HomeSectionHeader - 홈화면 섹션 헤더
- HomeSectionListItem - 리스트형식 아이템
- 내부에 있는 링크는 임시 링크입니다.
아무거나 샀어요가 추가되면 SectionCard 내에서 타입에 따라 그려지는 리스트가 다르게 할 예정입니다.
=> 홈화면 공통 헤더, 리스트 형식 공통 컴포넌트 UI 생성

src/components/editor/PostEditor.tsx, src/hooks/useAutoSaveDraft.ts, src/hooks/useRestoreDraft.ts, src/types/editor.ts, src/utils/editorStorage.ts
임시 저장 불러오기 전 이미 에디터에 표시되는 버그 수정 및 임시 저장 시 카테고리와 태그 제거
- 임시 저장 시 카테고리와 태그 정보를 저장하지 않도록 수정했습니다
- 자동 임시 저장 시 카테고리와 태그 정보를 저장하지 않도록 수정했습니다
- 에디터 접속 시 임시 저장한 내용이 먼저 보이지 않도록 수정했습니다
- 임시 저장 불러오기 모달에서 "아니오"를 누른 경우 임시 저장한 내용 자체를 삭제하도록 수정했습니다
로컬에서 에디터 페이지 테스트
구조가 바뀌면서 메인 카테고리가 보이지 않기 때문에 카테고리와 태그를 저장하면
오히려 버그날 확률이 높다는 생각이 들어서 아예 제거를 했습니다
이 부분은 다른 의견 있으시면 말씀 부탁드립니다
일단 불러오기 전 에디터 초기화랑 불러오기 모달은 작동이 잘 될 것 같은데 
배포 시 또 살펴봐야겠습니다 ㅠ
=> 임시 저장 불러오기 전 이미 에디터에 표시되는 버그 수정 및 임시 저장 시 카테고리와 태그 제거

src/components/layout/Header/Header.tsx, src/components/notification/NotificationHeader.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationModal.tsx
- 알림모달 컴포넌트 ui
- 헤더 알림버튼 누를 시 토글
- 헤더에 알림버튼 누를 시 알림모달 열고 닫음 추가 (useEffect)
- 알림모달 컴포넌트 & 내부 컨포넌트 1. 알림이벤트컴포넌트, 2. 알림헤더컴포넌트 UI
- 더미데이터 사용
- 데이터의 type에 따라 알림이벤트 ui 다르게 렌더링
> ![image](https://github.com/user-attachments/assets/2a4bdcf8-c95f-4dd1-9b03-ee11917f8c11)
- figma 디자인
> ![May-30-2025 10-49-40](https://github.com/user-attachments/assets/daab8116-2914-4fb6-9993-90f2e43784ef)
- 헤더에 연결 -> 헤더 있는 모든 페이지에서 알림모달 여닫음 가능
- 스크롤바 구현
> 
- 사이즈 / 미디어쿼리 참고 
- localhost 에서 UI 제작 (더미데이터 사용)
- 더 구현할 부분
- 모달 외부 클릭 시 모달 닫힘
- 알림아이템 호버링 추가
- username을 눌렀을 때, 상대방 프로필페이지 이동
- 알림 눌렀을 때 알림 읽음 처리 & 해당 페이지 이동
- 전체적 CSS (font 스타일링)
- createdAt은 localDateTime으로 전달할 예정이므로, 날짜 format 변경
- 등등 ..
=> Feat/notification : 알림모달 컴포넌트 ui, 헤더 알림버튼 누를 시 토글

src/components/notification/NotificationHeader.tsx, src/components/notification/NotificationItem.tsx, src/components/notification/NotificationModal.tsx, src/lib/api/notification.ts, src/types/notification.ts
- 알림목록조회 api 연결
- 개별알림읽기 api 연결
- 전체알림읽기 api 연결
- 리뷰 반영 : 공백 표시 교체
- #61 
- 썸네일 이미지에도 url 변환 유틸메서드 붙임
- 알림 유발 유저(?) 명칭 user -> actor로 교체 (BE 응답포맷도 같이 교체했습니다)
- 더미데이터 삭제하고 api 연결로 대체
> <img width="701" alt="스크린샷 2025-06-02 오후 4 56 55" src="https://github.com/user-attachments/assets/d8130086-2f7c-4048-8a8c-b3da05273d2d" />
> **알림목록조회 api 연결 (DB 반영, 최신순)**
> ![개별읽음](https://github.com/user-attachments/assets/8cff25fa-0716-4b80-bbb3-6898b424f000)
**개별 읽기 api 연결**
- 알림 아이템 클릭 시 기본적으로 해당 게시물/유저프로필 이동 & 알림 모달 닫힘
- 안읽은 알림 아이템 클릭 시 읽음 처리 추가 ('안읽음표시 == 보라색 점' 사라짐)
- api호출로 읽음처리 DB에 반영
> ![전체읽기](https://github.com/user-attachments/assets/b1b7dcef-0554-411e-9b69-1b442399bb41)
전체 읽기 api 연결
- 전체읽기 버튼 클릭 시, 안읽은 알림들 마저 읽음처리 (보라색 점 사라짐)
- 재렌더링으로 UI 즉시 반영 (알림조회 호출)
- api호출로 전체읽음처리 DB에 …
=> Feat/notification api : 알림목록조회, 개별알림읽기, 전체알림읽기 api 연결

src/app/favorite/[groupId]/FavoritePageClient.tsx, src/app/favorite/[groupId]/page.tsx, src/components/Profile/BookmarkGroupCard.tsx, src/components/Profile/BookmarkGroupList.tsx, src/components/Profile/FavoriteItemCard.tsx, src/hooks/useBookmarkGroups.ts, src/hooks/useFavoriteItems.ts, src/lib/api/bookmark.ts, src/lib/api/favorite.ts, src/types/favorite.ts
즐겨찾기 그룹 API 추가와 즐겨찾기 상세 UI 와 API 추가 
- 즐겨찾기 그룹 카드에서 메뉴 모달에 수정과 삭제 API 를 연결했습니다
- 즐겨찾기 그룹 리스트에서 그룹 추가 버튼을 임시로 만들었습니다 (그룹 추가를 프로필에서도 가능하게 할지 미정)
- 즐겨찾기 그룹 리스트에서 그룹 카드 이름을 누르면 해당 그룹의 상세 리스트 페이지로 이동합니다
- 즐겨찾기 상세 페이지와 카드 UI 를 구현했습니다 (그룹 이름, 장소 개수, 즐겨찾기 상세 리스트)(카드 안 정보는 임시)
- 즐겨찾기 카드에서도 메뉴 버튼과 모달을 구현했고, 메모 수정과 즐겨찾기 삭제 API 를 연결했습니다
- 즐겨찾기 삭제 상태가 된 카드는 리스트와 장소 개수에 반영되지 않도록 추가했습니다
( 프로필 즐겨찾기 그룹 리스트에서 해당 그룹의 리스트 상세로 이동할 수 있음 )
( 그룹 추가 버튼 임시 구현 )
( 현재 즐겨찾기 상세 리스트 )
( 메뉴 버튼 클릭 시 메모 수정 / 삭제 모달 )
( 메모를 수정 중인 상태 )
직접 실행 테스트
즐겨찾기 장소 카드에 표시할 정보는 수정할 예정입니다 !
장소 이름, 장소 주소, 메모 정도면 되지 않을까 싶은데 반환되는 어떤 정보든 더 표시할 수 있는 상태긴 합니다
즐겨찾기 상세에서 메뉴 모달에 "수정"을 "메모 수정"으로 바꾸는게 직관적이겠네요 이거는 바로 반영하겠습니다
그리고 즐겨찾기 그룹은 bookmark 라는 표현을 썼고, 즐겨찾기 상세는 favorite 표현을 사용한 상태라
API 명세에 따라 favorite 로 통일하는 리팩토링을 해야할 것 같습니다 ㅠ..
=> 즐겨찾기 그룹 API 추가와 즐겨찾기 상세 UI 와 API 추가

src/app/map/page.tsx, src/components/map/BookmarkInfo.tsx, src/components/map/KakaoMap.tsx, src/components/map/PlaceCard.tsx, src/components/map/PlaceModal.tsx, src/components/map/PlaceUserMemos.tsx, src/components/map/PlaceUserMemosHeader.tsx, src/components/map/UserMemoCard.tsx, src/components/map/UserMemoCards.tsx, src/lib/api/map.ts, src/types/map.ts
- 장소 리스트 컴포넌트와 상세 컴포넌트를 바꿔치기(?)하도록 수정, 즐겨찾기 리스트 API, 장소 상세 조회 API 연결
- kakaoMap에 컴포넌트 종속되어있던 것 분리
- 실제 API 응답객체 생성
- API 연결(인근 즐겨찾기 장소 조회, 장소 클릭 시 메모리스트 조회 API)
- 장소 클릭 시 컴포넌트 교체
https://github.com/user-attachments/assets/a976159e-2928-43c7-986d-8090b844d101
-> 클릭으로 왔다갔다 합니다 ㅠㅠ
-> api 연결 정상적으로 됩니다
- 로컬환경에서 직접 구동했습니다.
- npm run build 통과했습니당
- 상단에 "서울시 > 강남구" 는 아직 하드코딩 데이터입니다. 마커 생성 기능 작업할 때 함께 작업하도록 하겠습니다.
close #62
=> Feat/combine-component  컴포넌트 교체, 즐겨찾기리스트 조회, 장소 상세 조회 API 연결

src/app/map/page.tsx, src/components/layout/Footer/Footer.tsx, src/components/map/BookmarkInfo.tsx, src/components/map/PlaceCard.tsx, src/components/map/PlaceModal.tsx, src/components/map/PlaceUserMemos.tsx, src/components/map/PlaceUserMemosHeader.tsx, src/components/map/SideMenu.tsx, src/components/map/UserGroupList.tsx, src/components/map/UserMemoCard.tsx, src/components/map/UserMemoCards.tsx, src/lib/api/map.ts, src/stores/mapStore.ts, src/types/map.ts
- 유저 그룹 리스트 조회 UI 및 API 연결과 Zustand를 적용했습니다.
- 기존의 상태변수를 useState로 관리하는 방식에서 Zustand로 전역관리하도록 수정했습니다.
- 그룹 리스트 UI 구현
- 컴포넌트 간 전환 가능
- 해당 그룹을 클릭하면 해당 유저의 그룹 리스트가 조회됩니다.
> https://github.com/user-attachments/assets/762283ec-34e9-416a-8e6f-7e35091c993f
- 지도 페이지에서 인근 장소리스트를 조회하고, 장소를 클릭했을 때 유저들의 메모를 확인해볼 수 있습니다.
- 유저 클릭 시 해당 유저의 그룹 리스트를 조회할 수 있습니다.
- ⭐  현충일이니까 다들 쉬시고 월요일에 pr피드백 주셔도 좋습니다!!  ⭐ 
- 제가 코드에 확신이 없어서 한 커밋에 코드가 큼직큼직하게 들어가는 경우가 많습니다.. 커밋 잘 쪼개볼게요
- UI를 만들려다보니 데이터가 필요했고, 데이터를 불러오려고하니 useState로는 벅차서 Zustand까지 적용해버렸는데 브랜치 생성 의도와 맞지 않아서 다음부터는 유의해서 작업하도록 하겠습니다. PR 작업량이 너무 커져버렸네요..
> ![image](https://github.com/user-attachments/assets/c08a8db4-d071-4b0f-8342-b692fdd6c291)
- 이슈 #85 에서 API연동으로 수정할 예정입니다. 아직 백엔드 pr반영이 되지않아 작업못했습니다.
> ![image](https://github.com/user-attachments/assets/473008cd-cc …
=> UI/user-group-list 유저 그룹 리스트 UI, API 연결, Zustand 적용

src/app/map/page.tsx, src/components/map/FavoriteAddModal.tsx, src/components/map/KakaoMap.tsx, src/components/map/PlaceModal.tsx, src/components/map/PlaceUserMemos.tsx, src/components/map/PlaceUserMemosHeader.tsx, src/components/map/SideMenu.tsx, src/components/map/UserGroupList.tsx, src/lib/api/map.ts, src/stores/mapStore.ts
- 즐겨찾기 추가 모달 UI 생성 및 장소의 즐겨찾기 상태 API연결
- 테스트 버튼을 누르면 즐겨찾기 추가 모달이 펼쳐집니다.
- close 누르면 모달이 닫힙니다.
- 그룹 선택에서 "그룹 추가" 모달을 클릭하면 새 그룹이름을 입력할 수 있습니다.
- 그룹과 메모를 선택할 수 있습니다.
- 즐겨찾기 상태를 API 연결을 통해 불러오도록 수정했습니다.
https://github.com/user-attachments/assets/16d68956-f313-4e54-b2fc-f3951da67cb3
- 즐겨찾기 모달 테스트 
https://github.com/user-attachments/assets/86cc0aa0-1eda-4bf4-9cb1-4e02b66f4c70
- 즐겨찾기 상태 Star에 반영 및 클릭 불가능한 요소로 변경
- 임의의 데이터 (API 연결x) 로 지도 페이지에서 테스트했습니다.
close #85
=> UI/map-favorite 즐겨찾기 추가 모달 UI 및 장소의 즐겨찾기 상태 API연결

src/app/map/page.tsx, src/components/map/FavoriteCard.tsx, src/components/map/FavoriteList.tsx, src/components/map/GroupCard.tsx, src/components/map/GroupCardList.tsx, src/components/map/GroupsFavoriteList.tsx, src/components/map/KakaoMap.tsx, src/components/map/PlaceModal.tsx, src/components/map/PlaceUserMemos.tsx, src/components/map/PlaceUserMemosHeader.tsx, src/components/map/UserGroupList.tsx, src/components/map/UserMemoCard.tsx, src/lib/api/map.ts, src/stores/mapStore.ts, src/types/map.ts, src/utils/date.ts
- 유저의 그룹에 대한 즐겨찾기 조회 UI, API 연결
- zustand 적용
- 그룹의 즐겨찾기 리스트 조회 UI 
- 그룹의 즐겨찾기 리스트 조회 API 연결 완료
- 자취 시작일 정보 없을 시  "D + ? " 로 출력
- 자취 시작일 정보 있을 시 계산된 "D + ??" 로 출력
- 즐겨찾기 등록이 안되어있을 때 예외 메시지 "등록된 즐겨찾기가 없습니다" 출력
- D+day 계산 메서드 util에 추가
https://github.com/user-attachments/assets/33157a9c-63a0-4baf-a4dd-39c53225268c
- 각 그룹에 대한 즐겨찾기리스트를 조회하고, 즐겨찾기가 추가되어있지 않을 때 예외 메시지를 출력합니다.
> ![image](https://github.com/user-attachments/assets/c52a70d7-836a-4ef0-9cde-eedc7bf51d78)
> ![image](https://github.com/user-attachments/assets/f2457955-4af3-4033-97dd-d319a2abd5fa)
- 그룹 목록 페이지와 즐겨찾기 페이지에서 DB에 저장된 날짜를 기반으로 D+ 를 계산해줍니다.
> ![image](https://github.com/user-attachments/assets/28cb9caf-b1c3-4e70-9612-73a0ee2fe111)
- 해당 그룹의 즐겨찾기가 정상적으로 조회됩니다.
> ![image](https://github.com/user-attachments/assets/4d83aaaf-2ab8-445 …
=> Feat/user-like-list 유저의 그룹에 대한 즐겨찾기 조회 UI, API 연결

src/components/Setting/ProfileInfoSection.tsx, src/components/Setting/useProfileInfoSection.ts, src/components/common/Input/DateInput.tsx, src/lib/api/profile.ts, src/utils/date.ts
프로필 변경 API연결했습니다.
- 생년월일, 자취 일자의 형식이 yyyy.MM.dd 형식이 아니거나 미래이거나 이상한 날짜의 경우 오류를 출력하도록했습니다.
- 프로필 변경 API를 연결했습니다.
- UI상으론 ".", 서버에 전송할 때는 "-"형태로 보내야해서 형식을 변경하는 로직을 추가했습니다.
- 데이터 업데이트가 성공할경우 useAuth에도 반영이 되도록 했습니다.
=> 프로필 변경 API연결

src/components/auth/LoginForm/useLoginForm.ts, src/components/layout/Header/Header.tsx, src/components/notification/NotificationItem.tsx, src/hooks/useSse.ts, src/lib/api/notification.ts, src/stores/useAuthStore.ts, src/types/event-source-polyfill.d.ts
- SSE인증 header기반으로 ref(버그 해결), 연결 유지를 위한 ping 처리 등
- 비로그인상태에서 알림렌더링 제거, 조건부 썸네일 렌더링
- 토큰 전역변수로 관리 추가
- 로그인 성공 시 accessToken을 Zustand 전역 상태로 저장 (쿠키에서 꺼냄)
- 이후 모든 인증 요청에서 해당 전역 토큰 참조
- SSE는 기본적으로 크로스도메인 환경에서 쿠키를 전송하지 않기 때문에, 인증 정보를 전역 상태에서 꺼내는 방식으로 변경함
- SSE 쿠키 인증 → 헤더 인증 (event-source-polyfill 라이브러리)
- 기존 쿠키 인증에서 헤더(Authorization : Bearer) 방식으로 전환
- 기본 EventSource는 커스텀 헤더를 설정할 수 없기 때문에, 헤더 설정이 가능한 event-source-polyfill 사용
- SSE heartbeatTimeout 타임아웃 설정과 ping 받기 처리
- eventSource는 45초 이내에 새로운 이벤트 전송이 없으면, 연결을 끊고 자동 재연결이 됨 (현재경우 넉넉히 65초로 세팅해둠)
- 자동 재연결 시, 자동  header 인증은 불가능한 문제 발발 (자동 재연결 시 header가 다시 붙지 않음)
- 따라서 서버에서 30초마다 서버 연결 유지용 ping 전송하게 처리해둠
- 클라이언트에서는 heartbeatTimeout: 65초로 설정하여 연결 유지
- SSE 이벤트 미수신 시 자동 재연결되도록 구성
- ping이 날아오지 않을 때 (서버가 꺼지거나 문제가 생겼을 때) SSE는 무한 재연결 시도 루프를 타게 됨
- 이런 서버 …
=> Fix/sse notification : SSE인증 header기반으로 ref(버그 해결), 연결 유지를 위한 ping 처리, 비로그인상태에서 알림렌더링 제거, 조건부 썸네일 렌더링

src/components/auth/LoginForm/useLoginForm.ts
- 카카오로그인 시 sse 401 해결
- 카카오 로그인 시 토큰 전역저장에 kakaoAccessToken을 넣어서 했었습니다.. 수정해야지 해놓고 까먹었네요 죄삼다🫠
- `setUser(user);` 이후 쿠키에서 꺼내서 전역저장하는 것으로 수정
- local에서 카카오 로그인 자체가 405라서.. 머지 후 빠른 확인 하겠습니다 (높은 확률로 잘 작동 될 것이에요)
=> fix/kakao-sse : 카카오로그인 시 sse 401 해결

src/components/map/GroupsFavoriteList.tsx, src/components/map/PlaceUserMemosHeader.tsx, src/components/map/UserGroupList.tsx, src/stores/map/useMapFavoriteStore.ts, src/stores/map/useMapGroupStore.ts, src/stores/map/useMapPlaceStore.ts
- map페이지 컴포넌트에 이전 데이터 남아있다가 전환되는 문제 수정
- 인근 장소 조회 시, 이전 데이터가 남아있다가 전환되는 문제 수정
- 유저의 그룹리스트 조회 시, 이전 데이터가 남아있다가 전환되는 문제 수정그룹의 즐겨찾기 조회 시
- 이전 데이터가 남아있다가 전환되는 문제 수정
- 모두 뒤로가기 버튼에서 데이터 초기화하도록 하였습니다.
- npm run build 통과
- 멘토님한테 물어봤던 부분! 뒤로가기 버튼 클릭 시, 이전 데이터 초기화로 구현했습니다.
- close #108
=> Bug/prevdata-load map페이지 컴포넌트에 이전 데이터 남아있다가 전환되는 문제 수정

src/components/auth/LoginForm/useLoginForm.ts
- useLoginForm에서 토큰 전역저장 코드 되살림
- accessToken이 zustand에 저장되지 않아 SSE 연결이 실패하던 문제를 해결
- #149 에서 setToken을 useAuthStore에서 실행하도록 바꾸셨었는데, 이 경우 useSse 진입 시점에 zustand에 토큰 저장이 되지 않았더라구요...!
- 로그인 시점에서 useLoginForm 내부에서 쿠키에 저장된 accessToken을 직접 꺼내어 전역 상태에 저장하도록 수정했습니다 (이전 코드 일부)
> 변경 전 로그인 직후 콘솔로그
> 변경 이후 로그인 직후 콘솔로그 : useSse 진입 시점 토큰 찍힘+연결시도 정상
- local3000 <-> ec2
- @mini0212 님 변경코드 부분이라 검토 부탁드립니다!
=> fix/sse : useLoginForm에서의 토큰 전역저장 코드 복구

src/app/profile/[userId]/page.tsx, src/components/Favorite/FavoriteGroupCard.tsx, src/components/Favorite/FavoriteGroupList.tsx, src/components/Favorite/FavoriteItemCard.tsx, src/components/Home/Map/HotPlaceList.tsx, src/components/Profile/ProfileTab/ProfileTabClient.tsx, src/components/Profile/ProfileTab/ProfileTabContent.tsx, src/components/editor/EditorActions.tsx, src/components/post/PostFooter.tsx, src/components/post/ShareModal.tsx, src/hooks/useFavorite.ts, src/hooks/useKakaoInit.ts, src/types/kakao.d.ts, src/utils/shareToKakao.ts
즐겨찾기 그룹 조회 버그 수정과 카카오톡 공유하기 기능 구현 및 사용자 UX 개선
- 글쓰기 에디터에서 등록 버튼 색상이 변경되었습니다 (violet800)
- 다른 사용자의 프로필에서 해당 사용자의 즐겨찾기 그룹이 조회되도록 수정했습니다
- 다른 사용자의 즐겨찾기 그룹 리스트에서 그룹 추가와 메뉴 버튼이 보이지 않게 수정했습니다
- 다른 사용자의 즐겨찾기 장소 리스트에서 메뉴 버튼이 보이지 않게 수정했습니다
- 핫플레이스 리스트 FallbackMessage 가 비로그인 사용자일 경우 로그인 관련 메세지가 나오게 분기처리 했습니다 
- 게시글 카카오톡 공유하기 기능과 이를 선택할 수 있는 모달을 구현했습니다
에디터 등록 버튼 색상 변경
즐겨찾기 그룹 리스트가 해당 프로필 사용자로 조회되고, 내 프로필이 아닐 시 그룹 추가 버튼 삭제, 메뉴 버튼 삭제
즐겨찾기 장소 리스트에서 다른 사용자 조회 시 메뉴 버튼 삭제
비로그인 시 핫플레이스 리스트 FallbackMessage "로그인이 필요합니다." 로 분기 처리
게시글 카카오톡 공유하기 기능과 공유 선택 관련 모달 구현
npm run build 통과
작동 테스트
즐겨찾기 리스트도 메뉴 버튼 안보이게 해야겠네요 금방 처리하겠습니다 ! (완료)
다행히 카카오톡 공유하기는 카카오 개발자 페이지에서 신청할 게 따로 없는 것 같습니다 !
대신 같이 전송될 사진이나 메세지는 기본에서 추가한게 없어서 설정하는 법만 좀 더 살펴보고 
다른 사이트 방식 참고해서 수정해보겠습니다
=> 즐겨찾기 그룹 조회 버그 수정과 카카오톡 공유하기 기능 구현 및 사용자 UX 개선

src/lib/api/map.ts
유저 근처 정보 받아올 때 access token 보내지 않도록 수정
- 홈에서 401 오류 발생해서 access token을 보내지않도록 수정했습니다.
=> 유저 근처 정보 받아올 때 access token 보내지 않도록 수정

src/components/map/KakaoMap.tsx
- 검색 결과 모달 위치 수정
- 중앙에 있으면 안되는데 일정 너비 이후 화면의 중앙 아래 위치하는 버그 수정!! 
- 모바일 환경, pc환경 모두 확인 완료!
=> bug : 검색 결과 모달 위치 수정

src/components/map/UserMemoCard.tsx
- 유저 메모 이미지+이름+메모 배치구조 개선
- 닉네임이 길 때 어색한 문제 UI 수정으로 개선
- 기존의 UI
- 개선된 UI
- npm run build 통과
- 커밋 이름이 fire인건 실수입니다! 양해바랍니다
=> ref/model : 유저 메모 이미지+이름+메모 배치구조 개선
