code-is-evenly-cooked/even-zaro-front

- .env.example
- package-lock.json
- package.json
- src/app/api/auth/[...nextauth]/route.ts
- src/app/layout.tsx
- src/app/login/page.tsx
- src/components/auth/LoginForm/LoginForm.tsx
- src/components/auth/LoginForm/useLoginForm.ts
- src/components/auth/Signup/KakaoLoginButton.tsx
- src/components/common/Button/IconButton.tsx
- src/providers/Providers.tsx
- src/types/agreement.d.ts
- src/types/next-auth.d.ts
로그인 UI를 작업하고 카카오 로그인 버튼 추가 및 카카오 로그인 연결했습니다.
- next-auth를 활용해 카카오 로그인을 생성했습니다.
- 로그인 UI를 만들었습니다.
- 카카오 로그인 버튼은 여기만 사용할 것 같아서 공통 버튼으로 만들지 않고 따로 생성했습니다.
- iconButton에 xl타입 추가, 약관의 인터페이스가 지난 pr에 누락되어서 추가했습니다.
원래 저 로딩중이 카카오 로그인입니다ㅎㅎ.. 로그인이나 회원가입 이후 세션정보 삭제하면 카카오 로그인으로 다시 보일거에요...ㅎ
> 로그인UI 및 카카오 로그인 연결

- src/lib/api/auth.ts
비밀번호 재설정 오탈자 수정
- 비밀번호 재설정 링크 오탈자 수정했습니다
- resetpassword parameter 오탈자 수정했습니다.
아까 수정하고 머지했어야했는데 빌드오류 수정이 급해서 수정못하고 머지해버렸네요.
죄송합니다.
> 비밀번호 재설정 오탈자 수정

- .env.example
- src/app/board/[category]/[postId]/page.tsx
- src/app/board/[category]/page.tsx
- src/components/Home/HomeComponent.tsx
- src/components/Home/HomeSectionCard.tsx
- src/components/common/SectionCards/PostImageCard.tsx
- src/components/common/SectionCards/PostListCard.tsx
- src/components/editor/PostEditor.tsx
- src/components/layout/Header/Header.tsx
- src/components/post/PostAuthor.tsx
- src/lib/api/posts.ts
- src/stores/useAuthStore.ts
- src/stores/usePostStore.ts
- src/types/post.ts
이미지 키 값 네이밍 변경
#29 이미지 키 네이밍 변경 
- profileImageUrl -> profileImage
- thumbnailUrl -> thumbnailImage
- imageUrlList -> postImageList
- 이미지url 링크용 환경변수 추가
배포 정상적으로 동작하는 것 확인했습니다.
> 이미지 키 값 네이밍 변경

- src/components/common/SectionCards/PostListCard.tsx
- src/utils/image.ts
저장 누락 파일 추가
- 마크다운 replace 커밋 누락 파일 추가
> 저장 누락 파일 추가

- src/app/board/[category]/[postId]/page.tsx
- src/components/Profile/BookmarkGroup.tsx
- src/components/Profile/ProfileHeader.tsx
- src/components/Profile/ProfileTabs.tsx
- src/components/post/PostFooter.tsx
- src/hooks/useProfile.ts
- src/types/profile.ts
#56 PR과 관련된 리뷰 사항 수정 반영
- 게시글 상세 페이지 category 부분을 상수로 선언해 리펙토링 했습니다
- 프로필에서 userId 가 없는 경우 조건을 추가했습니다 (Hooks을 조건문 안에서 사용하면 안 된다는 오류 때문에 일단 이렇게 처리해봤습니다)
- 카테고리 탭 리스트 html 구조를 ul 과 li 로 변경했습니다
- 프로필 불러오기 API 와 훅을 client.ts 로 리펙토링하고 응답 타입을 별도로 분리했습니다
- 기타 오탈자와 아이콘을 수정했습니다
#56 PR 리뷰해주신 사항 수정하고 커밋까지 진행했는데 push 안하고 머지해버렸습니다.. 죄송합니다..
> #56 PR과 관련된 리뷰 사항 수정 반영

- src/components/layout/Header/Header.tsx
Vercel 배포 오류 수정
- Header.tsx에서 해당 코드가 사라져 hideHeaderRoutes unuse로 인한 vercel 배포 오류 수정했습니다.
> Vercel 배포 오류 수정

- src/components/layout/Header/Header.tsx
- Header.tsx import 누락 수정
- 수동 conflict 이외 부분이었는데... main코드의 import가 자동으로 들어갈 줄 알았으나, 안들어갔습니다ㅠㅠ
머지 직후 빠른 수정
- 오류 제거, 헤더 작동
> fix : Header.tsx import 누락 수정

- package-lock.json
- package.json
- src/components/post/Comment/CommentAction.tsx
- src/components/post/Comment/CommentInput.tsx
- src/components/post/Comment/CommentListItem/CommentEditForm.tsx
- src/components/post/Comment/CommentSection.tsx
- src/components/post/Comment/useCommentList.ts
- src/lib/api/comment.ts
- src/stores/useCommentLoadingStore.ts
- src/stores/useCommentReply.ts
- src/utils/comment.tsx
- src/utils/date.ts
답글 UI, 글자 제한, 로딩표시, 시간 포맷팅변경
- 답글 버튼을 클릭할 경우 데이터 전달을 위한 전역 저장소를 만들었습니다.
- 댓글 생성 api를 comment.ts로 이동했습니다.
- 글자 제한 추가했습니다(500자)
- 텍스트가 없을 경우 등록버튼을 disabled했습니다.
- 댓글 쓰기, 수정, 삭제 로딩을 추가했습니다.
- 댓글 날짜 포맷팅을 변경했습니다. 
- date-fns-tz를 통해 적용했는데 한국시간 기준으로 변경을해도 값 변화가 없길래 강제로 UTC변환 후 다시 KST로 하니 제가 원하는 시간이 나왔습니다. 서버에서 KST 기준으로 주고 있는 것 같아 내일 델스때 말씀드려볼생각입니다.
|글자 개수 제한|댓글 입력 로딩|
|--|--|
|<img width="780" alt="스크린샷 2025-06-04 오후 6 25 36" src="https://github.com/user-attachments/assets/1a7fc49e-235e-41e7-8acd-cb7efe809174" />|<img width="812" alt="스크린샷 2025-06-04 오후 10 07 33" src="https://github.com/user-attachments/assets/375d7d7b-7a50-4e6d-abf5-a6e1646ed0b0" />|
|댓글 수정 로딩|댓글 삭제 로딩|
|<img width="782" alt="스크린샷 2025-06-04 오후 10 08 18" …
> 답글 UI, 글자 제한, 로딩표시, 시간 포맷팅변경

- src/app/setting/page.tsx
- src/components/Profile/ProfileHeader/ProfileHeader.client.tsx
- src/components/Profile/ProfileHeader/ProfileHeader.tsx
- src/components/Setting/ProfileInfoSection.tsx
- src/components/Setting/SettingComponent.tsx
- src/components/common/Input/BaseInput.tsx
- src/components/layout/Header/Header.tsx
- src/lib/fetch/client.ts
계정정보 페이지 생성 및 기본정보 섹션 UI
- 계정 정보 페이지를 구현했습니다.
- 계정정보 내 기본정보 섹션을 추가했습니다.
- 데이터 뿌리는건 api연결 우선적으로 하고 작업하도록 하겠습니다!
> 계정정보 페이지 생성 및 기본정보 섹션 UI

- src/components/Setting/SettingComponent.tsx
- src/components/layout/Sidebar/Sidebar.tsx
회원 탈퇴, 로그아웃 토스트 적용
- 회원 탈퇴 실패 alert -> toast 메시지 변경
- 로그아웃 실패 toast 적용 
- 다른 분들 리뷰 보다가 까먹기 전에 작업했습니다. UX적으로 필요 없을 것 같은 부분은 따로 추가하지 않았습니다.
> 회원 탈퇴, 로그아웃 토스트 적용

- src/app/favorite/[groupId]/FavoritePageClient.tsx
- src/components/Favorite/AddFavoriteGroupModal.tsx
- src/components/Favorite/ConfirmDeleteModal.tsx
- src/components/Favorite/FavoriteGroupCard.tsx
- src/components/Favorite/FavoriteGroupList.tsx
- src/components/Favorite/FavoriteHeader.tsx
- src/components/Favorite/FavoriteItemCard.tsx
- src/components/Profile/ProfileHeader/ProfileHeader.tsx
- src/components/Profile/ProfileHeader/Stat.tsx
- src/components/Setting/WithdrawConfirmModal.tsx
- src/components/common/Modal/BaseModal.tsx
- src/components/editor/RestoreDraftModal.tsx
- src/types/favorite.ts
즐겨찾기 장소 이름과 장소 개수 연결 및 추가와 삭제 시 모달, 반응형 작업
- 즐겨찾기 장소 이름과 그룹의 장소 개수가 하드 코딩 되어있던 부분을 API 와 연결했습니다
- 즐겨찾기 관련하여 프론트에서 deleted 로 필터링 하는 코드를 삭제하였습니다
- 즐겨찾기 그룹 추가 시 프롬프트가 아닌 모달이 등장하도록 구현하고 추가했습니다
- 즐겨찾기 그룹 삭제와 즐겨찾기 장소 삭제 시 모달이 등장하도록 구현하고 추가했습니다
- 프로필 페이지와 즐겨찾기 페이지를 와이어프레임에 맞게 모바일 반응형 디자인을 추가했습니다
모바일에서 프로필 화면
모바일 즐겨찾기 리스트 페이지에서 프로필 화면
그룹 추가 시 확인 모달
그룹 삭제 시 확인 모달
장소 삭제 시 확인 모달
npm run build 통과
기능 동작 테스트
PR 을 정리해서 드리는게 좋을 것 같아서 프로필과 즐겨찾기 우선 올립니다
게시글 쪽도 작업이 어느정도 마무리됬는데 리팩토링을 우선 진행하고 추가로 PR 드리도록 하겠습니다 !
에디터 버그도 가능하면 오늘 안으로 고칠 수 있도록 해보겠습니다
작업 완료되서 PR 추가로 드리면 될 것 같습니다 🙌
> 즐겨찾기 장소 이름과 장소 개수 연결 및 추가와 삭제 시 모달, 반응형 작업

- next.config.ts
- src/app/board/[category]/[postId]/page.tsx
- src/components/Favorite/FavoriteHeader.tsx
- src/components/Profile/ProfileHeader/ProfileHeader.tsx
- src/components/map/GroupsFavoriteList.tsx
- src/components/map/UserGroupList.tsx
- src/lib/api/post.server.ts
- src/types/post.ts
- src/utils/date.ts
디데이 계산 로직 추가.
- PostDetailResponse에 user를 추가해서 빌드 실패 오류를 해결했습니다.
- close #101 
- 자취 시작일이 있을 경우 표기하도록 했습니다.
- 일반 flex일 경우는 공백으로만 처리, flex-col일때는 그려지지않도록 예외처리 했습니다.
- close #123 cc. @yoorym-kim 
|flex|flex-col|
|--|--|
|<img width="1167" alt="스크린샷 2025-06-12 오후 7 57 34" src="https://github.com/user-attachments/assets/c8b46ea7-7351-4889-9a29-a3537698d27d" />|<img width="612" alt="스크린샷 2025-06-12 오후 7 57 38" src="https://github.com/user-attachments/assets/3d546ab9-12ca-46f9-a077-650d6f58bb55" />|
> 디데이 계산 로직 추가

- next.config.ts
> CSP 방어코드 제거

- middleware.ts
- public/init-kakao.js
- src/app/layout.tsx
카카오 지도 로드 오류 수정
-  카카오 지도 api 키 적용하지 않아 생겼던 로드실패를 수정했습니다.
-
> fix: 카카오 지도 로드 오류 수정

- src/app/profile/[userId]/loading.tsx
- src/app/profile/[userId]/not-found.tsx
- src/app/profile/[userId]/page.tsx
- src/components/AuthInitializer.tsx
- src/components/Profile/ProfileHeader/ProfileHeader.tsx
- src/components/Profile/ProfilePostList.tsx
- src/components/Profile/ProfileTab/ProfileTabContent.tsx
- src/components/post/PostAuthor.tsx
- src/hooks/useProfileItemList.ts
- src/lib/api/profile.ts
- src/types/profile.ts
프로필 없을 경우 예외처리 및 팔로우버튼 추가
- close #136 @yoorym-kim 제안하신 프로필에 팔로우 버튼 추가
- 내 프로필일경우 설정버튼을, 다른 사람의 프로필일경우 팔로우 버튼 표시
- 팔로우 시 팔로워 +1되도록 수정(팔로우취소도 동일)
- 존재하지 않는 회원의 경우 not-found 페이지로 연결
- not-found page사용하게 되면서 csr로 통신중이였던 api를 ssr로 변경해야했음
- useSuspenseQuery 사용 시 쿠키 내부의 access token을 가져오지 못하는 이슈가 있어서 useQuery로 변경 
|내 프로필|남 프로필|
|--|--|
|<img width="832" alt="image" src="https://github.com/user-attachments/assets/be0763d1-7e20-49d4-8847-b3d5137cb52e" />|<img width="816" alt="image" src="https://github.com/user-attachments/assets/f6f59add-9eb2-4228-a203-f7ab9de1175e" />|
|존재하지 않거나 탈퇴한 회원|
> 프로필 없을 경우 예외처리 및 팔로우버튼 추가

- src/components/Profile/Modal/UserFollowItem.tsx
- src/components/layout/Footer/Footer.tsx
- src/lib/api/follow.ts
팔로우 관련 버그 수정
- 팔로우 리스트에서 데이터가 서버와 싱크가 맞지 않은 부분 수정
- 팔로잉 리스트에서 유저 클릭 시 프로필 이동
- 팔로잉 리스트 버튼 디자인 다른곳과 동일하게 변경
- 푸터 위치기반 서비스 이용약관 텍스트 삭제
|팔로우 리스트|
|--|
|<img width="428" alt="image" src="https://github.com/user-attachments/assets/05db62c5-834b-4bb9-adcc-460e1716e55a" />|
|푸터 약관 리스트|
|<img width="908" alt="image" src="https://github.com/user-attachments/assets/16fe035d-57e8-4450-b90d-e918e0d64596" />|
> 팔로우 관련 버그 수정

- package-lock.json
- package.json
- src/components/Home/PopularPostList.tsx
- src/lib/api/popular.ts
undefined -> 해당 Category로 나오는거 확인, 인기게시글 애니메이션추가
- install farmer-motion  애니메이션 추가
- 순위에 따라 배경효과 부여
<br>
<br>
https://github.com/user-attachments/assets/e8129bda-2fad-4db3-9c65-37ccfa81d239
인기게시글 순위변동시 배경효과 나타나는지 동영상 촬영
아이콘을 넣고싶어서 다시 시도해봤는데 여전히 잘 안되어서 배경효과를 주는것으로 일단 수정했습니다..!
혹시나 불필요하다 말씀주신다면 롤백하겠슴당 🙇‍♀️
> Feat/post: 인기게시글 수정

- src/components/Favorite/FavoriteHeader.tsx
- src/components/Home/HomeSectionCard.tsx
- src/components/Home/HomeSectionImageItem.tsx
- src/components/Profile/Modal/UserFollowItem.tsx
- src/components/Profile/ProfileHeader/ProfileHeader.tsx
- src/components/Setting/ProfileImageUploader.tsx
- src/components/common/SectionCards/PostImageCard.tsx
- src/components/common/SectionCards/PostListCard.tsx
- src/components/layout/Header/Header.tsx
- src/components/layout/Header/HeaderSkeleton.tsx
- src/components/map/BookmarkInfo.tsx
- src/components/map/GroupsFavoriteList.tsx
- src/components/map/SideMenu.tsx
- src/components/map/UserGroupList.tsx
- src/components/post/Comment/CommentListItem/index.tsx
- src/components/post/PostAuthor.tsx
데이터 추가 중 버그 수정
- 게시글 리스트에서 게시글 가로 영역 넘어가는 이슈 수정
- 프로필 이미지 1:1 적용
- 헤더 스켈레톤과 mt 다른 부분 수정
-
> 데이터 추가 중 버그 수정

- src/components/map/KakaoMap.tsx
- 검색어 예시 삭제
- 기존의 예시 검색어 이태원 맛집을 제거했습니다.
- npm run build 통과
> Ref/del-serach-sample 검색어 예시 삭제

- src/components/notification/NotificationModal.tsx
- 알림모달 모바일 비율, 위치 맞춤 적용
- 모바일환경에서 다음과 같은 밀림현상
- 배포 후 모바일로 확인
- local3000
- 팁 있다면 도와주세용 fe여러분!
> style/noti-modal : 알림모달 모바일 비율, 위치 맞춤 적용

- src/app/board/[category]/page.tsx
페이지네이션 오류 수정
- 페이지네이션 조건을 잘못 적어서 상세 리스트에서 페이지네이션 버튼이 나오지 않는 이슈를 수정했습니다.
-
> 페이지네이션 오류 수정
